apiVersion: v1
kind: Service
metadata:
  name: my-nginx
  labels:
    run: my-nginx
spec:
  ports:
  - port: 80
    targetPort: 9376
    protocol: TCP
  selector:
    run: my-nginx
  type: LoadBalancer
